//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarResonanceDpsAnalysis.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarResonanceDpsAnalysis.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 678150498（1群）.
        /// </summary>
        public static string About_Community_GroupOne {
            get {
                return ResourceManager.GetString("About_Community_GroupOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1022797551（2群）.
        /// </summary>
        public static string About_Community_GroupTwo {
            get {
                return ResourceManager.GetString("About_Community_GroupTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法访问 GitHub 或者想要寻求游戏伙伴也可以加QQ群：.
        /// </summary>
        public static string About_Community_Invite {
            get {
                return ResourceManager.GetString("About_Community_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果你想为本项目贡献代码，欢迎 Fork 之后提交 Pull Request。.
        /// </summary>
        public static string About_Contribution {
            get {
                return ResourceManager.GetString("About_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2025 anying1073/StarResonanceDps Team..
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尻鸭（ihonliu）.
        /// </summary>
        public static string About_Developer_Ihonliu {
            get {
                return ResourceManager.GetString("About_Developer_Ihonliu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 惊奇猫猫盒（anying1073：项目发起者）.
        /// </summary>
        public static string About_Developer_Lead {
            get {
                return ResourceManager.GetString("About_Developer_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青岚宗王腾.
        /// </summary>
        public static string About_Developer_QingLan {
            get {
                return ResourceManager.GetString("About_Developer_QingLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 露詩（Rocy-June）.
        /// </summary>
        public static string About_Developer_RocyJune {
            get {
                return ResourceManager.GetString("About_Developer_RocyJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本的开发者们（排名不分先后）:.
        /// </summary>
        public static string About_Developers_Label {
            get {
                return ResourceManager.GetString("About_Developers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该工具无需修改游戏客户端，不违反游戏服务条款。该工具旨在帮助玩家更好地理解战斗数据，减少不必要的精力消耗，提升游戏体验。使用该工具前，请确保不会将数据结果用于战力歧视等破坏游戏社区环境的行为。.
        /// </summary>
        public static string About_Intro_Details {
            get {
                return ResourceManager.GetString("About_Intro_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一款专为《星痕共鸣》玩家打造的战斗数据统计工具。.
        /// </summary>
        public static string About_Intro_Primary {
            get {
                return ResourceManager.GetString("About_Intro_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本项目于.
        /// </summary>
        public static string About_OpenSource_Prefix {
            get {
                return ResourceManager.GetString("About_OpenSource_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/anying1073/StarResonanceDps.
        /// </summary>
        public static string About_OpenSource_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_OpenSource_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中开源，如在使用中遇到问题可以直接提出 Issue。.
        /// </summary>
        public static string About_OpenSource_Suffix {
            get {
                return ResourceManager.GetString("About_OpenSource_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by .NET 8, Licensed under the GNU AGPL v3..
        /// </summary>
        public static string About_PoweredBy {
            get {
                return ResourceManager.GetString("About_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此感谢.
        /// </summary>
        public static string About_Thanks_Prefix {
            get {
                return ResourceManager.GetString("About_Thanks_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/dmlgzs/StarResonanceDamageCounter.
        /// </summary>
        public static string About_Thanks_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_Thanks_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目对于本项目的帮助于支持.
        /// </summary>
        public static string About_Thanks_Suffix {
            get {
                return ResourceManager.GetString("About_Thanks_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本号：.
        /// </summary>
        public static string About_Version_Label {
            get {
                return ResourceManager.GetString("About_Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别查我DPS.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启.
        /// </summary>
        public static string Common_Action_Open {
            get {
                return ResourceManager.GetString("Common_Action_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Common_Dash {
            get {
                return ResourceManager.GetString("Common_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以上数据仅供娱乐与参考，严禁用于战力歧视等破坏游戏社区环境的行为；一经发现，永久取消该功能的使用资格。.
        /// </summary>
        public static string DamageReference_Disclaimer {
            get {
                return ResourceManager.GetString("DamageReference_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Breakdown.
        /// </summary>
        public static string DamageReference_Header_Title {
            get {
                return ResourceManager.GetString("DamageReference_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无数据.
        /// </summary>
        public static string DamageReference_NoData {
            get {
                return ResourceManager.GetString("DamageReference_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全职业.
        /// </summary>
        public static string DamageReference_Profession_All {
            get {
                return ResourceManager.GetString("DamageReference_Profession_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考.
        /// </summary>
        public static string DamageReference_Ribbon_Title {
            get {
                return ResourceManager.GetString("DamageReference_Ribbon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考.
        /// </summary>
        public static string DamageReference_Table_Title {
            get {
                return ResourceManager.GetString("DamageReference_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSampleData.
        /// </summary>
        public static string Debug_AddSampleData {
            get {
                return ResourceManager.GetString("Debug_AddSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Test Log.
        /// </summary>
        public static string Debug_AddTestLog {
            get {
                return ResourceManager.GetString("Debug_AddTestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scroll.
        /// </summary>
        public static string Debug_AutoScroll {
            get {
                return ResourceManager.GetString("Debug_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于窗口.
        /// </summary>
        public static string Debug_Button_About {
            get {
                return ResourceManager.GetString("Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考窗口.
        /// </summary>
        public static string Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcap 测试.
        /// </summary>
        public static string Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置窗口.
        /// </summary>
        public static string Debug_Button_Settings {
            get {
                return ResourceManager.GetString("Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情窗口.
        /// </summary>
        public static string Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        public static string Debug_ClearLogs {
            get {
                return ResourceManager.GetString("Debug_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Debug_Filter_Label {
            get {
                return ResourceManager.GetString("Debug_Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string Debug_Filter_Level {
            get {
                return ResourceManager.GetString("Debug_Filter_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter logs by message or category content.
        /// </summary>
        public static string Debug_Filter_Tooltip {
            get {
                return ResourceManager.GetString("Debug_Filter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试功能.
        /// </summary>
        public static string Debug_Group_Title {
            get {
                return ResourceManager.GetString("Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Debug_Header_Category {
            get {
                return ResourceManager.GetString("Debug_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Debug_Header_Level {
            get {
                return ResourceManager.GetString("Debug_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Debug_Header_Message {
            get {
                return ResourceManager.GetString("Debug_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Debug_Header_Time {
            get {
                return ResourceManager.GetString("Debug_Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load PCAP.
        /// </summary>
        public static string Debug_LoadPcap {
            get {
                return ResourceManager.GetString("Debug_LoadPcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        public static string Debug_SaveLogs {
            get {
                return ResourceManager.GetString("Debug_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤：.
        /// </summary>
        public static string Debug_Status_FilteredPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  条日志.
        /// </summary>
        public static string Debug_Status_FilteredSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新：.
        /// </summary>
        public static string Debug_Status_LastPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_LastPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总计：.
        /// </summary>
        public static string Debug_Status_TotalPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  条日志.
        /// </summary>
        public static string Debug_Status_TotalSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题切换测试文本.
        /// </summary>
        public static string Debug_ThemeTestText {
            get {
                return ResourceManager.GetString("Debug_ThemeTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鼠标穿透已启用.
        /// </summary>
        public static string DpsStatistics_Indicator_ClickThrough_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_Indicator_ClickThrough_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string DpsStatistics_TestButton_Content {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加测试数据.
        /// </summary>
        public static string DpsStatistics_TestButton_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于窗口.
        /// </summary>
        public static string MainWindow_Debug_Button_About {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考窗口.
        /// </summary>
        public static string MainWindow_Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcap 测试.
        /// </summary>
        public static string MainWindow_Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置窗口.
        /// </summary>
        public static string MainWindow_Debug_Button_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情窗口.
        /// </summary>
        public static string MainWindow_Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试功能.
        /// </summary>
        public static string MainWindow_Debug_Group_Title {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题切换测试文本.
        /// </summary>
        public static string MainWindow_Debug_ThemeTest {
            get {
                return ResourceManager.GetString("MainWindow_Debug_ThemeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别查我 D P S.
        /// </summary>
        public static string MainWindow_Header_Title {
            get {
                return ResourceManager.GetString("MainWindow_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [官方] 别查我DPS 开发团队.
        /// </summary>
        public static string MainWindow_Plugin_Author_OfficialTeam {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Author_OfficialTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自启动.
        /// </summary>
        public static string MainWindow_Plugin_AutoStart {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提供DPS统计、技能分解等功能.
        /// </summary>
        public static string MainWindow_Plugin_DpsTool_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_DpsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS工具.
        /// </summary>
        public static string MainWindow_Plugin_DpsTool_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_DpsTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者：.
        /// </summary>
        public static string MainWindow_Plugin_Label_Author {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简介：.
        /// </summary>
        public static string MainWindow_Plugin_Label_Intro {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Label_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提供模组快速计算最优解功能.
        /// </summary>
        public static string MainWindow_Plugin_ModuleSolver_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_ModuleSolver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组求解器.
        /// </summary>
        public static string MainWindow_Plugin_ModuleSolver_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_ModuleSolver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过大量的玩家在线数据互助，提供小猪娜宝的线路与位置信息.
        /// </summary>
        public static string MainWindow_Plugin_PigTracker_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_PigTracker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小猪娜宝状态查看器.
        /// </summary>
        public static string MainWindow_Plugin_PigTracker_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_PigTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过大量的玩家在线数据互助，提供各线路的野外BOSS存活状态等信息.
        /// </summary>
        public static string MainWindow_Plugin_WorldBoss_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_WorldBoss_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 野外BOSS状态查看器.
        /// </summary>
        public static string MainWindow_Plugin_WorldBoss_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_WorldBoss_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件列表.
        /// </summary>
        public static string MainWindow_PluginList_Title {
            get {
                return ResourceManager.GetString("MainWindow_PluginList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史记录.
        /// </summary>
        public static string Menu_History {
            get {
                return ResourceManager.GetString("Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人模式.
        /// </summary>
        public static string Menu_PersonalMode {
            get {
                return ResourceManager.GetString("Menu_PersonalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录每一次.
        /// </summary>
        public static string Menu_Record_Always {
            get {
                return ResourceManager.GetString("Menu_Record_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不记录1分钟以下.
        /// </summary>
        public static string Menu_Record_Skip1Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip1Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不记录2分钟以下.
        /// </summary>
        public static string Menu_Record_Skip2Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip2Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录设置.
        /// </summary>
        public static string Menu_RecordSettings {
            get {
                return ResourceManager.GetString("Menu_RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示总伤.
        /// </summary>
        public static string Menu_ShowTotal {
            get {
                return ResourceManager.GetString("Menu_ShowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能日记.
        /// </summary>
        public static string Menu_SkillDiary {
            get {
                return ResourceManager.GetString("Menu_SkillDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能显示.
        /// </summary>
        public static string Menu_SkillDisplay {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示全部.
        /// </summary>
        public static string Menu_SkillDisplay_All {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前 10 条.
        /// </summary>
        public static string Menu_SkillDisplay_Top10 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前 15 条.
        /// </summary>
        public static string Menu_SkillDisplay_Top15 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前 5 条.
        /// </summary>
        public static string Menu_SkillDisplay_Top5 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前 8 条.
        /// </summary>
        public static string Menu_SkillDisplay_Top8 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计BOSS.
        /// </summary>
        public static string Menu_StatisticBoss {
            get {
                return ResourceManager.GetString("Menu_StatisticBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打桩模式.
        /// </summary>
        public static string Menu_Training {
            get {
                return ResourceManager.GetString("Menu_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极限打桩.
        /// </summary>
        public static string Menu_Training_Extreme {
            get {
                return ResourceManager.GetString("Menu_Training_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 协会打桩.
        /// </summary>
        public static string Menu_Training_Faction {
            get {
                return ResourceManager.GetString("Menu_Training_Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人打桩.
        /// </summary>
        public static string Menu_Training_Personal {
            get {
                return ResourceManager.GetString("Menu_Training_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分析模组.
        /// </summary>
        public static string ModuleSolve_Analyze_Button {
            get {
                return ResourceManager.GetString("ModuleSolve_Analyze_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除词条（与目标词条冲突）[可输入文字索引].
        /// </summary>
        public static string ModuleSolve_ExcludeProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_ExcludeProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期望等级：.
        /// </summary>
        public static string ModuleSolve_ExpectedLevel_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ExpectedLevel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组求解器.
        /// </summary>
        public static string ModuleSolve_Header_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string ModuleSolve_ModuleType_All {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防御模组.
        /// </summary>
        public static string ModuleSolve_ModuleType_Defense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组类型：.
        /// </summary>
        public static string ModuleSolve_ModuleType_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻击模组.
        /// </summary>
        public static string ModuleSolve_ModuleType_Offense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Offense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助模组.
        /// </summary>
        public static string ModuleSolve_ModuleType_Support {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性1：.
        /// </summary>
        public static string ModuleSolve_Property1_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性2：.
        /// </summary>
        public static string ModuleSolve_Property2_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性3：.
        /// </summary>
        public static string ModuleSolve_Property3_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性4：.
        /// </summary>
        public static string ModuleSolve_Property4_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性5：.
        /// </summary>
        public static string ModuleSolve_Property5_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性优先.
        /// </summary>
        public static string ModuleSolve_Sort_Attribute {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序方式：.
        /// </summary>
        public static string ModuleSolve_Sort_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级优先.
        /// </summary>
        public static string ModuleSolve_Sort_Level {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标词条和等级（0为默认）[可输入文字索引].
        /// </summary>
        public static string ModuleSolve_TargetProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_TargetProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开此界面后需要过图或者重新登陆一次才能进行分析【右键属性选项为清空当前选项】.
        /// </summary>
        public static string ModuleSolve_UsingTip {
            get {
                return ResourceManager.GetString("ModuleSolve_UsingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三位计数法 (KMBT).
        /// </summary>
        public static string NumberDisplay_KMB {
            get {
                return ResourceManager.GetString("NumberDisplay_KMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四位计数法 (万亿兆).
        /// </summary>
        public static string NumberDisplay_Wan {
            get {
                return ResourceManager.GetString("NumberDisplay_Wan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冰魔导师.
        /// </summary>
        public static string Profession_FrostMage {
            get {
                return ResourceManager.GetString("Profession_FrostMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巨刃守护者.
        /// </summary>
        public static string Profession_HeavyGuardian {
            get {
                return ResourceManager.GetString("Profession_HeavyGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神射手.
        /// </summary>
        public static string Profession_Marksman {
            get {
                return ResourceManager.GetString("Profession_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神盾骑士.
        /// </summary>
        public static string Profession_ShieldKnight {
            get {
                return ResourceManager.GetString("Profession_ShieldKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 灵魂乐手.
        /// </summary>
        public static string Profession_SoulMusician {
            get {
                return ResourceManager.GetString("Profession_SoulMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷影剑士.
        /// </summary>
        public static string Profession_Stormblade {
            get {
                return ResourceManager.GetString("Profession_Stormblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 森语者.
        /// </summary>
        public static string Profession_VerdantOracle {
            get {
                return ResourceManager.GetString("Profession_VerdantOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青岚骑士.
        /// </summary>
        public static string Profession_WindKnight {
            get {
                return ResourceManager.GetString("Profession_WindKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前.
        /// </summary>
        public static string ScopeTime_Current {
            get {
                return ResourceManager.GetString("ScopeTime_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全程.
        /// </summary>
        public static string ScopeTime_Total {
            get {
                return ResourceManager.GetString("ScopeTime_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脱战后清除当前统计.
        /// </summary>
        public static string Settings_Combat_ClearAfterBattle {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换地图时清空全程统计.
        /// </summary>
        public static string Settings_Combat_ClearAfterTeleport {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        public static string Settings_Common_Seconds {
            get {
                return ResourceManager.GetString("Settings_Common_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计数显示类型.
        /// </summary>
        public static string Settings_Display_NumberMode {
            get {
                return ResourceManager.GetString("Settings_Display_NumberMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗体透明度.
        /// </summary>
        public static string Settings_Display_Opacity {
            get {
                return ResourceManager.GetString("Settings_Display_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings_Heading {
            get {
                return ResourceManager.GetString("Settings_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string Settings_Language_Auto {
            get {
                return ResourceManager.GetString("Settings_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监听网卡.
        /// </summary>
        public static string Settings_NetworkAdapter_Label {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动设置错误时可手动设置.
        /// </summary>
        public static string Settings_Section_Basic_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础设置.
        /// </summary>
        public static string Settings_Section_Basic_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 脱战清空只重置当前战斗数据，而非全程统计.
        /// </summary>
        public static string Settings_Section_Combat_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战斗设置.
        /// </summary>
        public static string Settings_Section_Combat_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置.
        /// </summary>
        public static string Settings_Section_Display_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择界面语言.
        /// </summary>
        public static string Settings_Section_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string Settings_Section_Language_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按下 Delete 删除选择的键位.
        /// </summary>
        public static string Settings_Section_Shortcut_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按键设置.
        /// </summary>
        public static string Settings_Section_Shortcut_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空数据.
        /// </summary>
        public static string Settings_Shortcut_ClearData {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此聚焦并按下快捷键（例如 F9）。按 Delete 清除。.
        /// </summary>
        public static string Settings_Shortcut_ClearData_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鼠标穿透.
        /// </summary>
        public static string Settings_Shortcut_MouseThrough {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此聚焦并按下组合键（例如 Ctrl+F6）。按 Delete 清除。.
        /// </summary>
        public static string Settings_Shortcut_MouseThrough_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关.
        /// </summary>
        public static string Settings_Switch_Off {
            get {
                return ResourceManager.GetString("Settings_Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开.
        /// </summary>
        public static string Settings_Switch_On {
            get {
                return ResourceManager.GetString("Settings_Switch_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害分布.
        /// </summary>
        public static string SkillBreakdown_Card_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS/HPS/DTPS实时曲线图.
        /// </summary>
        public static string SkillBreakdown_Card_RealtimeChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_RealtimeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能占比分布图.
        /// </summary>
        public static string SkillBreakdown_Card_ShareChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_ShareChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情.
        /// </summary>
        public static string SkillBreakdown_Header_Title {
            get {
                return ResourceManager.GetString("SkillBreakdown_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 臂章: 190.
        /// </summary>
        public static string SkillBreakdown_Info_Badge {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级: 60.
        /// </summary>
        public static string SkillBreakdown_Info_Level {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --测试名称--.
        /// </summary>
        public static string SkillBreakdown_Info_Name {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战力: 25000.
        /// </summary>
        public static string SkillBreakdown_Info_Power {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID: 123456.
        /// </summary>
        public static string SkillBreakdown_Info_Uid {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均伤害.
        /// </summary>
        public static string SkillBreakdown_Label_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击次数.
        /// </summary>
        public static string SkillBreakdown_Label_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击伤害.
        /// </summary>
        public static string SkillBreakdown_Label_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击率.
        /// </summary>
        public static string SkillBreakdown_Label_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受击次数.
        /// </summary>
        public static string SkillBreakdown_Label_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒伤.
        /// </summary>
        public static string SkillBreakdown_Label_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命中次数.
        /// </summary>
        public static string SkillBreakdown_Label_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运次数.
        /// </summary>
        public static string SkillBreakdown_Label_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运伤害.
        /// </summary>
        public static string SkillBreakdown_Label_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运率.
        /// </summary>
        public static string SkillBreakdown_Label_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通伤害.
        /// </summary>
        public static string SkillBreakdown_Label_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总伤害.
        /// </summary>
        public static string SkillBreakdown_Label_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个条形图.
        /// </summary>
        public static string SkillBreakdown_Placeholder_BarChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详情占位.
        /// </summary>
        public static string SkillBreakdown_Placeholder_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个表单.
        /// </summary>
        public static string SkillBreakdown_Placeholder_Form {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图表占位.
        /// </summary>
        public static string SkillBreakdown_Placeholder_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个折线图.
        /// </summary>
        public static string SkillBreakdown_Placeholder_LineChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个饼图.
        /// </summary>
        public static string SkillBreakdown_Placeholder_PieChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害分布.
        /// </summary>
        public static string SkillBreakdown_Section_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害信息.
        /// </summary>
        public static string SkillBreakdown_Section_DamageInfo {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string SkillBreakdown_Tab_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string SkillBreakdown_Tab_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 治疗.
        /// </summary>
        public static string SkillBreakdown_Tab_Healing {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出.
        /// </summary>
        public static string SkillBreakdown_Tab_Output {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SkillBreakdown_Tab_Summary {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承伤.
        /// </summary>
        public static string SkillBreakdown_Tab_Tanking {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Tanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7106.
        /// </summary>
        public static string SkillBreakdown_Value_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SkillBreakdown_Value_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.92K.
        /// </summary>
        public static string SkillBreakdown_Value_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.67%.
        /// </summary>
        public static string SkillBreakdown_Value_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string SkillBreakdown_Value_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.01K.
        /// </summary>
        public static string SkillBreakdown_Value_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string SkillBreakdown_Value_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SkillBreakdown_Value_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SkillBreakdown_Value_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        public static string SkillBreakdown_Value_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.71K.
        /// </summary>
        public static string SkillBreakdown_Value_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.64K.
        /// </summary>
        public static string SkillBreakdown_Value_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害.
        /// </summary>
        public static string StatisticType_Damage {
            get {
                return ResourceManager.GetString("StatisticType_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 治疗.
        /// </summary>
        public static string StatisticType_Healing {
            get {
                return ResourceManager.GetString("StatisticType_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC承伤.
        /// </summary>
        public static string StatisticType_NpcTakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_NpcTakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承伤.
        /// </summary>
        public static string StatisticType_TakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_TakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换为：全程 / 当前.
        /// </summary>
        public static string Tooltip_ToggleScope {
            get {
                return ResourceManager.GetString("Tooltip_ToggleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string Window_About_Title {
            get {
                return ResourceManager.GetString("Window_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考.
        /// </summary>
        public static string Window_DamageReference_Title {
            get {
                return ResourceManager.GetString("Window_DamageReference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug View.
        /// </summary>
        public static string Window_Debug_Title {
            get {
                return ResourceManager.GetString("Window_Debug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DpsStatisticsForm.
        /// </summary>
        public static string Window_DpsStatistics_Title {
            get {
                return ResourceManager.GetString("Window_DpsStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组求解器.
        /// </summary>
        public static string Window_ModuleSolve_Title {
            get {
                return ResourceManager.GetString("Window_ModuleSolve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Window_Settings_Title {
            get {
                return ResourceManager.GetString("Window_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情.
        /// </summary>
        public static string Window_SkillBreakdown_Title {
            get {
                return ResourceManager.GetString("Window_SkillBreakdown_Title", resourceCulture);
            }
        }
    }
}
